import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="facebook-domain-verification"
          content="dpmcab7a29fw9hk1vhwxi6xn0gi9d0"
        />
      </head>
      <body className="antialiased">{children}</body>
    </html>
  );
}
